---
title: "Clean_luca"
output:
  pdf_document: default
  html_document: default
date: "2024-12-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading in all necessary packages

library(here) 
library(ggplot2) 
library(readxl) 
library(sf) 
library(cowplot)
library(rnaturalearth)
library(ggspatial)
library(dplyr)
library(tidyverse)
library(circular)
library(knitr)
library(glmmTMB)
library(DHARMa)
library(ggeffects)
library(performance)
library(car)
library(mgcv)
library(fitdistrplus)
library(goft)
library(gamlss)
```

```{r}
#load in data, change temperature to factor, remove extra space in "conspecific"
nudi_data_factor <- read.csv("./clean_data/Meyknecht_Over_Parker_MRNE475_2024_combinedraw.csv")%>%
  mutate(temp_grp = as.factor(temp_grp))
nudi_data_factor$trial_type[nudi_data_factor$trial_type=="conspecific "] <- "conspecific"

```

```{r}
#make linear model with nudi data with interaction between temp and length
mod_nudi <- lm(mean_vel ~ temp_grp * avg_length_m, 
             data = nudi_data_factor)

#plot simulated residuals to see whether it fits
simulateResiduals(mod_nudi)%>%
  plot()

#summary of the linear model
summary(mod_nudi)
```


```{r}
#fit model into gamma as interaction (temp*length)
nudi_gamma_factor_times <- glmmTMB(mean_vel ~ temp_grp * avg_length_m, family = Gamma(link = "log"), data = nudi_data_factor)

#fit simulated residuals in plot to see whether it fits (red means it doesn't, no red means it does)
simulateResiduals(nudi_gamma_factor_times)%>%
  plot()

#summarize the model
summary(nudi_gamma_factor_times)

# Extract the coefficients
coef_table <- as.data.frame(summary(nudi_gamma_factor_times)$coefficients$cond)

# Save the table as a CSV file
write.csv(coef_table, "./luca_scripts/Meyknecht_Over_Parker_MRNE475_2024_nudi_gamma_factor_times_coefficients.csv", row.names = TRUE)
```

```{r}

#creating my own color palette for the different temp groups
my_cols <- c("12" = "red", "14" = "darkblue","16" = "green", "18"= "yellow" )

#boxplot mean velocity for different temperature groups without jitter
boxplot_nudi <- ggplot(nudi_data_factor, aes(x=temp_grp, y=mean_vel, fill=temp_grp)) + 
    geom_boxplot(alpha=0.3) +
  scale_fill_manual(values = my_cols) +
  labs(y = "Mean velocity (m/s)\n", x = "\nTemperature (°C)", 
       color = "Treatment group (°C)", 
       fill = "Treatment group (°C)") +
  theme_classic()

#boxplot mean velocity for diffrent temperature groups with jitter
boxplot_jitter_nudi <- ggplot(nudi_data_factor, aes(x=temp_grp, y=mean_vel, fill=temp_grp)) + 
   geom_point(aes(colour = temp_grp), position = position_jitterdodge()) +
    geom_boxplot(alpha=0.3) +
  scale_color_manual(values = my_cols) +
  scale_fill_manual(values = my_cols) +
  labs(y = "Mean velocity (m/s)\n", x = "\nTemperature (°C)", 
       color = "Treatment group(°C)", 
       fill = "Treatment group(°C)") +
  theme_classic()

#same boxplot, different theme
boxplot_nudi_goodtheme <- ggplot(nudi_data_factor, aes(x=temp_grp, y=mean_vel, fill=temp_grp)) + 
    geom_boxplot(alpha=0.3) +
  scale_fill_manual(values = my_cols) +
  labs(y = "Mean velocity (m/s)\n", x = "\nTemperature (°C)", 
       color = "Treatment group (°C)", 
       fill = "Treatment group (°C)") +
theme_minimal() +
  theme(
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    axis.line = element_line(color = "black", size = 0.5),  # Add axis lines for both x and y axes
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks to both x and y axes
    axis.title.x = element_text(margin = margin(t = 10)),  # Add space between x-axis labels and numbers
    axis.title.y = element_text(margin = margin(r = 10)),  # Add space between y-axis labels and numbers
    strip.text = element_text(size = 12, face = "bold", margin = margin(b = 20))  # Add space between facet labels and graph
  )

#show plots
boxplot_nudi
boxplot_jitter_nudi
boxplot_nudi_goodtheme

#save plots as picture
ggsave(plot = boxplot_nudi, filename = here("luca_scripts","Meyknecht_Over_Parker_MRNE475_2024_boxplot_nudi.pdf"), width = 6, height = 4)
ggsave(plot = boxplot_jitter_nudi, filename = here("luca_scripts","Meyknecht_Over_Parker_MRNE475_2024_boxplot_jitter_nudi.pdf"), width = 6, height = 4)
ggsave(plot =boxplot_nudi_goodtheme, filename = here("luca_scripts", "Meyknecht_Over_Parker_MRNE475_2024_goodboxplot.png"), bg = "white", width = 6, height = 4)


```

```{r}
#print citations fro packages
print(citation("DHARMa"), style = "text")
print(citation("glmmTMB"), style = "text")
citation()

```

```{r}
#summarize the mean velocity for each temp group to get all the boxplot values + mean
summary(nudi_data_factor$mean_vel[nudi_data_factor$temp_grp=="12"])
summary(nudi_data_factor$mean_vel[nudi_data_factor$temp_grp=="14"])
summary(nudi_data_factor$mean_vel[nudi_data_factor$temp_grp=="16"]) 
summary(nudi_data_factor$mean_vel[nudi_data_factor$temp_grp=="18"]) 

#average and se of mean velocity
nudi_data_factor %>%
group_by(temp_grp) %>%
summarize(mean = mean(mean_vel)*100,
se = (sd(mean_vel)/sqrt(length(mean_vel)))*100)


```


```{r}
# Calculate the average mean velocity for each temp_grp
mean_values <- nudi_data_factor %>%
  group_by(temp_grp) %>%
  summarise(mean_mean_vel = mean(mean_vel, na.rm = TRUE))

# create boxplot with average mean velocity per temp group in there aswell
boxplot_nudi <- ggplot(nudi_data_factor, aes(x = temp_grp, y = mean_vel, fill = temp_grp)) + 
  geom_boxplot(alpha = 0.3)  +
  scale_fill_manual(values = my_cols) +
  geom_point(data = mean_values, aes(x = temp_grp, y = mean_mean_vel), 
             color = "black", size = 3, shape = 21, fill="black") +
  labs(
    y = "Mean velocity (m/s)\n", 
    x = "\nTemperature (°C)", 
    color = "Treatment group (°C)", 
    fill = "Treatment group (°C)"
  ) +
 theme_minimal() +
  theme(
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    axis.line = element_line(color = "black", size = 0.5),  # Add axis lines for both x and y axes
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks to both x and y axes
    axis.title.x = element_text(margin = margin(t = 10)),  # Add space between x-axis labels and numbers
    axis.title.y = element_text(margin = margin(r = 10)),  # Add space between y-axis labels and numbers
    strip.text = element_text(size = 12, face = "bold", margin = margin(b = 20))  # Add space between facet labels and graph
  )

#show plot
boxplot_nudi

#save plot as picture
ggsave(plot =boxplot_nudi, filename = here("luca_scripts", "Meyknecht_Over_Parker_MRNE475_2024_perfectplot.png"), bg = "white", width = 6, height = 4)
```


```{r}
#plot mean velocity and average length with points and glm, to see the relationship between the two
nudi_vel_length <- ggplot(nudi_data_factor, aes(x= avg_length_m, y = mean_vel)) +
  geom_point(size = 2) +
  labs(
    y = "Mean velocity (m/s)", 
    x = "Average length (m)") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
    axis.line = element_line(color = "black", size = 0.5),  # Add axis lines for both x and y axes
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks to both x and y axes
    axis.title.x = element_text(margin = margin(t = 10)),  # Add space between x-axis labels and numbers
    axis.title.y = element_text(margin = margin(r = 10)),  # Add space between y-axis labels and numbers
    strip.text = element_text(size = 12, face = "bold", margin = margin(b = 20))  # Add space between facet labels and graph
  )+
  geom_smooth(method = "glm", color = "darkgrey", fill = "lightgrey")

#save as picture
ggsave(plot = nudi_vel_length, filename = here("luca_scripts","Meyknecht_Over_Parker_MRNE475_2024_lm_length_vel2.png"), width = 6, height = 4, bg="white")

nudi_vel_length
```

