---
title: "Nudi_tryout1"
output: pdf_document
date: "2024-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here) #loading data
library(ggplot2) #plotting data
library(readxl) #importing excel files
library(sf) #for spatial data
library(cowplot)
library(rnaturalearth)
library(ggspatial)
library(dplyr)
library(tidyverse)
install.packages("circular")
library(circular)
```


```{r}
nudi_con <- read.csv("./nudidata/cons_trial.csv")
```



```{r}
# Libraries


 
# Make the plot
p <- ggplot(nudi_con, aes(x=as.factor(temp_grp), y= fixdeg)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  # This add the bars with a blue color
  geom_bar(stat="identity", fill=alpha("blue", 0.3)) +
  
  # Limits of the plot = very important. The negative value controls the size of the inner circle, the positive one is useful to add size over each bar
  ylim(-100,120) +
  
  # Custom the theme: no axis title and no cartesian grid
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-2,4), "cm")     # This remove unnecessary margin around plot
  ) +
  
  # This makes the coordinate polar instead of cartesian.
  coord_polar(start = 0)
p
```
```{r chatgpt tryout}

data_avg_gr <- nudi_con %>%
  group_by(nudi_num, temp_grp) %>% 
  summarise(avg_angle = mean(fixdeg,na.rm = TRUE), .groups = "drop")

data_avg <- nudi_con %>%
  group_by(nudi_num) %>% 
  summarise(avg_angle = mean(fixdeg,na.rm = TRUE), .groups = "drop")

data_avg <- nudi_con %>%
  group_by(nudi_num) %>% 
  summarise(avg_angle = mean(circular(fixdeg, units = "degrees")),na.rm = TRUE, .groups = "drop")

data <- data %>%
  left_join(data_avg, by = "trial")

ggplot(data_avg_gr, aes(x = avg_angle, y = nudi_num, color = temp_grp)) +
  geom_point(size = 3, alpha = 0.8) +  # Points sized and slightly transparent
  coord_polar(start = pi / 2) +  # Convert to polar coordinates
  scale_x_continuous(breaks = seq(0, 360, 45), limits = c(0, 360)) +  # Custom axis
  labs(title = "Circular Graph of Trial Angles by Treatment",
       x = "Angle (Degrees)",
       y = "Trial") +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal() +  # Clean theme
  theme(legend.position = "bottom") 
```

