---
title: "Graphs"
author: "Fiona Parker"
date: "2024-12-07"
output: html_document
---

this is the code for our circular data graphs - we did not include this graph in our final paper

```{r}
#loading in all my packages
library(here) 
library(ggplot2) 
library(readxl) 
library(sf) 
library(cowplot)
library(rnaturalearth)
library(ggspatial)
library(dplyr)
library(tidyverse)
library(circular)

#loading in all my data 

nudi_con <- read.csv("./raw_data/Meyknecht_Over_Parker_MRNE475_2024_rawcons.csv")
trial_data <- read.csv("./raw_data/Meyknecht_Over_Parker_MRNE475_2024_rawtrialdata.csv")
nudi_preds <- read.csv("./raw_data/Meyknecht_Over_Parker_MRNE475_2024_rawpred.csv")
```

```{r}

# here i am making each graph that we will be makings its own little data set -> this data set will then be complied into 2 groups of 4 to give us two four paneled graphs that demonstrate the mean angular direction of each nudibranch in each treatment group

clean_con12 <- nudi_con%>%
  filter(temp_grp == 12) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()


 avg12 <- clean_con12 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 

clean_con14 <- nudi_con%>%
  filter(temp_grp == 14) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

 avg14 <- clean_con14 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 
 
 clean_con16 <- nudi_con%>%
  filter(temp_grp == 16) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

avg16 <- clean_con16 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 
 
 clean_con18 <- nudi_con%>%
  filter(temp_grp == 18) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

 avg18 <- clean_con18 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 
 nudi_pred <- nudi_preds%>%
  rename(temp_grp = temp)

clean_pred12 <- nudi_pred%>%
  filter(temp_grp == 12) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

 avg12p <- clean_pred12 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 
 
clean_pred14 <- nudi_pred%>%
  filter(temp_grp == 14) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

 avg14p <- clean_pred14 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 
 
 clean_pred16 <- nudi_pred%>%
  filter(temp_grp == 16) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

avg16p <- clean_pred16 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
 
 
 clean_pred18 <- nudi_pred%>%
  filter(temp_grp == 18) %>%
  dplyr::select(nudi_num, temp_grp, fixdeg, rawdeg) %>%
  na.omit()

 avg18p <- clean_pred18 %>%
   group_by(nudi_num) %>%
   summarise(mean_angle = mean(fixdeg, na.rm = TRUE))
```

```{r}
#four panel pred plot results - basic with large size 

#this is the graph for the four paneled predator plot, i set the graph to be circular data opposed to x and y axis and then using ggplot made the specifications of the graph. then using patchwork i created all four plots using the same specifications from the circle plot and i put them all together in one graph. this was saved to plots_circle. 
create_circular_plot <- function(data, color, title, base_radius = 4, point_alpha = 0.5, point_size = 5) {
  circle_data <- data.frame(
    mean_angle = seq(0, 360, by = 1),  
    y = base_radius                    
  )

  ggplot(data, aes(x = mean_angle, y = base_radius)) +
    geom_point(size = point_size, alpha = point_alpha, fill = color, color = "black", shape = 21) +
    geom_path(data = circle_data, aes(x = mean_angle, y = y), color = "black", size = 0.5) +
    coord_polar(theta = "x", start = pi/2, clip = "off") +
    scale_x_continuous(
      breaks = c(0, 90, 180, 270),
      labels = c("0°", "90°", "180°", "270°")
    ) +
    scale_y_continuous(limits = c(0, 4.1)) +
    labs(title = title, x = "Mean Angular Movement (°)", y = NULL) +
    theme_minimal() +
    theme(
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid = element_blank(),
      plot.margin = unit(c(1, 1, 1, 1), "cm"),
      axis.text.x = element_text(margin = margin(-10, 0, 0, 0), size = 14),  
      plot.title = element_text(size = 16, face = "bold"),                   
      axis.title.x = element_text(size = 14)                          
    )
}


library(patchwork) 
plot_12 <- create_circular_plot(avg12p, "red", "12°C")
plot_14 <- create_circular_plot(avg14p, "blue", "14°C")
plot_16 <- create_circular_plot(avg16p, "green", "16°C")
plot_18 <- create_circular_plot(avg18p, "orange", "18°C")


four_panel_plot <- (plot_12 | plot_14) / (plot_16 | plot_18)


four_panel_plot


ggsave("./plots_circle/Meyknecht_Over_Parker_MRNE475_2024_four_panel_plot_pred_results.png", plot = four_panel_plot, width = 12, height = 12, dpi = 300)

```

```{r}
#cons four paneled graph 

#this was made the same way as the predator 4 panel except with the cons data

create_circular_plot <- function(data, color, title, base_radius = 4, point_alpha = 0.5, point_size = 5) {
  circle_data <- data.frame(
    mean_angle = seq(0, 360, by = 1), 
    y = base_radius                   
  )

  ggplot(data, aes(x = mean_angle, y = base_radius)) +
    geom_point(size = point_size, alpha = point_alpha, fill = color, color = "black", shape = 21) +
    geom_path(data = circle_data, aes(x = mean_angle, y = y), color = "black", size = 0.5) +
    coord_polar(theta = "x", start = pi/2, clip = "off") +
    scale_x_continuous(
      breaks = c(0, 90, 180, 270),
      labels = c("0°", "90°", "180°", "270°")
    ) +
    scale_y_continuous(limits = c(0, 4.1)) +
    labs(title = title, x = "Mean Angular Movement (°)", y = NULL) +
    theme_minimal() +
    theme(
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid = element_blank(),
      plot.margin = unit(c(1, 1, 1, 1), "cm"),
      axis.text.x = element_text(margin = margin(-10, 0, 0, 0), size = 14),  
      plot.title = element_text(size = 16, face = "bold"),                   
      axis.title.x = element_text(size = 14)                              
    )
}

library(patchwork) 

plot_12 <- create_circular_plot(avg12, "red", "12°C")
plot_14 <- create_circular_plot(avg14, "blue", "14°C")
plot_16 <- create_circular_plot(avg16, "green", "16°C")
plot_18 <- create_circular_plot(avg18, "orange", "18°C")


four_panel_plot_c <- (plot_12 | plot_14) / (plot_16 | plot_18)


four_panel_plot_c


ggsave("./plots_circle/Meyknecht_Over_Parker_MRNE475_2024_four_panel_plot_cons_results.png", plot = four_panel_plot_c, width = 12, height = 12, dpi = 300)

```

```{r}
#this is the same but i shrink down the panels 
create_circular_plot <- function(data, color, title, base_radius = 4, point_alpha = 0.5, point_size = 1.5, line_size = 0.3) {
  circle_data <- data.frame(
    mean_angle = seq(0, 360, by = 1),  
    y = base_radius                    
  )
  
  ggplot(data, aes(x = mean_angle, y = base_radius)) +
    geom_point(size = point_size, alpha = point_alpha, fill = color, color = "black", shape = 21) +
    geom_path(data = circle_data, aes(x = mean_angle, y = y), color = "black", size = line_size) +
    coord_polar(theta = "x", start = pi/2, clip = "off") +
    scale_x_continuous(
      breaks = c(0, 90, 180, 270),
      labels = c("0°", "90°", "180°", "270°")
    ) +
    scale_y_continuous(limits = c(0, 4.1)) +
    labs(title = title, x = "Mean Angular Movement (°)", y = NULL) +
    theme_minimal() +
    theme(
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm")  
    )
}

library(patchwork)

plot_12 <- create_circular_plot(avg12, "red", "12°C", point_size = 1.5, line_size = 0.3)
plot_14 <- create_circular_plot(avg14, "blue", "14°C", point_size = 1.5, line_size = 0.3)
plot_16 <- create_circular_plot(avg16, "green", "16°C", point_size = 1.5, line_size = 0.3)
plot_18 <- create_circular_plot(avg18, "orange", "18°C", point_size = 1.5, line_size = 0.3)

four_panel_plot_c <- (plot_12 | plot_14) / (plot_16 | plot_18)

ggsave(
  "./plots_circle/Meyknecht_Over_Parker_MRNE475_2024_four_panel_plot_cons_resultssmall.png",
  plot = four_panel_plot_c,
  width = 8.5 / 2,  
  height = 5.5,     
  dpi = 300,
  units = "in"
)


```


```{r}
#smaller pred
create_circular_plot <- function(data, color, title, base_radius = 4, point_alpha = 0.5, point_size = 1.5, line_size = 0.3) {
  circle_data <- data.frame(
    mean_angle = seq(0, 360, by = 1),  
    y = base_radius                   
  )
  
  ggplot(data, aes(x = mean_angle, y = base_radius)) +
    geom_point(size = point_size, alpha = point_alpha, fill = color, color = "black", shape = 21) +
    geom_path(data = circle_data, aes(x = mean_angle, y = y), color = "black", size = line_size) +
    coord_polar(theta = "x", start = pi/2, clip = "off") +
    scale_x_continuous(
      breaks = c(0, 90, 180, 270),
      labels = c("0°", "90°", "180°", "270°")
    ) +
    scale_y_continuous(limits = c(0, 4.1)) +
    labs(title = title, x = "Mean Angular Movement (°)", y = NULL) +
    theme_minimal() +
    theme(
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      panel.grid = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm") 
    )
}

library(patchwork)

plot_12 <- create_circular_plot(avg12p, "red", "12°C", point_size = 1.5, line_size = 0.3)
plot_14 <- create_circular_plot(avg14p, "blue", "14°C", point_size = 1.5, line_size = 0.3)
plot_16 <- create_circular_plot(avg16p, "green", "16°C", point_size = 1.5, line_size = 0.3)
plot_18 <- create_circular_plot(avg18p, "orange", "18°C", point_size = 1.5, line_size = 0.3)

four_panel_plot_c <- (plot_12 | plot_14) / (plot_16 | plot_18)

ggsave(
  "./plots_circle/Meyknecht_Over_Parker_MRNE475_2024_four_panel_plot_pred_resultssmall.png",
  plot = four_panel_plot_c,
  width = 8.5 / 2,  
  height = 5.5,     
  dpi = 300,
  units = "in"
)

```













